### ISSUE TITLE
[Q] How is this related to ContextMenu?

### ISSUE THREAD

**Issue by gingerbeardman** [Mortennn/FiScript#13]
The FiScript interface seems too similar to [ContextMenu.app](https://itunes.apple.com/app/context-menu/id1236813619?l=en&mt=12) to be a coincidence?

ContextMenu - [July 2017](https://langui.net/2017/07/context-menu-1-0-macos-released/)
FiScript - [July 2018](https://github.com/Mortennn/FiScript/commit/ecf096fd4c729138bb4f346985db2f135b1fd8e2)

What's the story?

**Comment by Mortennn** [comment]
I started developing FiScript before ContextMenu was released. FiScript has never been an attempt to be a clone of ContextMenu.

Though, for good measure, I have contacted the developer of ContextMenu and asked if there is anything he wants to have changed.

**Comment by gingerbeardman** [comment]
That's fine, I don't really mine either way.

I'm just intrigued that the interfaces turned out so similar?

**Comment by Mortennn** [comment]
I saw ContextMenu later on, and there were a few things he did right. But I will, of course, change that back if he wishes.

**Comment by gingerbeardman** [comment]
I don't see the need unless they _really_ object.

Thanks for making this app!

**Comment by Mortennn** [comment]
Glad you like it 😃
