### ISSUE TITLE
Multiple selected file Support?

### ISSUE THREAD

**Issue by elsonwx** [Mortennn/FiScript#14]
The `$PATH` variable only support one selected file.
When I choose multiple files in Findler,the program seems has not passed it to shell script

**Comment by gingerbeardman** [comment]
What does your shell script look like?

**Comment by elsonwx** [comment]
bash,I want to use `$@` in script  for  all selected files path,it seems no working.

**Comment by gingerbeardman** [comment]
This opens all selected files with their default app: 
```sh
open $PATH
```

So does this:
```sh
echo $PATH | xargs open
```

This may be more what you want: loop through each item of $PATH:
```sh
for p in $PATH; do
    open "$p"
done
```

**Comment by elsonwx** [comment]
@gingerbeardman It's working,thanks.
It turns out selected multiple files will run the bash script multiple times.
the `$PATH` represent the current loop file in selected files.
So it seems that script can't get all file list.
