### ISSUE TITLE
How to add new actions?

### ISSUE THREAD

**Issue by fabiospampinato** [Mortennn/FiScript#2]
This project seems interesting, but I see no mention on how new actions can be added to the context menu, that might be useful for newcomers.

**Comment by Mortennn** [comment]
Click the "plus"-sign to add new scripts to the context menu😀
<img width="817" alt="skaermbillede 2018-10-12 kl 03 01 54" src="https://user-images.githubusercontent.com/34214574/46841999-53a24a00-cdcb-11e8-9a72-b7bdbacfe93b.png">
